# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d84c4d1dcc9429c89495dadc0517fe4aabe8a44adadd4aa1b295c402668838ccc20bd638468693c69b9fd6bd91b847b84e02bbe1bd88bc8b06ef5dac89a8a1ea

test:
  secret_key_base: e6f32b5ac13f88922d2fa831acc8f4ca9fe761acb6349a1b7cfa21c2543cdaeb3866922b29c27088a4dd0b6c2cf32aa7a9f9f8b46c0237f44718e0f2ac45b8a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
